file:
  dir:
    product: /home/ukjjangstudy/rentshop/files/products/


spring:
  datasource:
    url : jdbc:mysql://localhost:3306/rentshop?serverTimezone=Asia/Seoul
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

jwt:
  secret: "1234567890123456789012345678901234567890"